[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "openusd"
version = "0.1.0"
description = "Universal Scene Description (USD) build scripts"
requires-python = ">=3.12.11"
dependencies = []

[project.scripts]
build_usd = "build_scripts.cli:build_usd_main"
build_usd_full = "build_scripts.cli:build_usd_full_main"

[tool.hatch.build.targets.wheel]
packages = ["build_scripts"]

[dependency-groups]
dev = [
    "jinja2>=3.1.6",
    "pyopengl>=3.1.10",
    "pyside6>=6.11.2",
]
